/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import controladores.DatoControlador;
import dao.Conexion;
import dao.DDato;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Dato;

/**
 *
 * @author Josar
 */
public class RevisionExpediente extends javax.swing.JFrame {

    /**
     * Creates new form RevisionExpediente
     */
    public RevisionExpediente() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension tamanyo = toolkit.getScreenSize();
        setLocation(tamanyo.width / 2 - getWidth() / 2, tamanyo.height / 2 - getHeight() / 2);
        
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoIncapacidad = new javax.swing.ButtonGroup();
        grupoAlergia = new javax.swing.ButtonGroup();
        grupoEjercicio = new javax.swing.ButtonGroup();
        grupoDesayuno = new javax.swing.ButtonGroup();
        grupoTabaquismo = new javax.swing.ButtonGroup();
        grupoAlcoholismo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaExpediente = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblNacimiento = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblTipoDeFecha = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        radioIncapacidadSi = new javax.swing.JRadioButton();
        radioIncapacidadNo = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        radioAlergiaSi = new javax.swing.JRadioButton();
        radioAlergiaNo = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        radioEjercicioSi = new javax.swing.JRadioButton();
        radioEjercicioNo = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        radioDesayunoSi = new javax.swing.JRadioButton();
        radioDesayunoNo = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        radioTabaquismoSi = new javax.swing.JRadioButton();
        radioTabaquismoNo = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        radioAlcoholismoSi = new javax.swing.JRadioButton();
        radioAlcoholismoNo = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblSangre = new javax.swing.JLabel();
        tfAltura = new javax.swing.JTextField();
        tfPeso = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnAyuda = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tfHereditarios = new javax.swing.JTextField();
        tfPatologicos = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaNotasPaciente = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfSueño = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        tfReligion = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tfTelefono = new javax.swing.JTextField();
        tfCasa = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaDireccion = new javax.swing.JTextArea();
        tfMunicipio = new javax.swing.JTextField();
        tfDepartamento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Revisión expediente");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tablaExpediente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaExpediente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaExpedienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaExpediente);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Información"));

        jLabel4.setText("Cédula");

        jLabel5.setText("Sexo");

        jLabel6.setText("Nacimiento");

        jLabel7.setText("Edad");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTipoDeFecha))
                            .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblCedula))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblSexo))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblNacimiento)
                    .addComponent(lblTipoDeFecha))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblEdad)
                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecciones"));

        jLabel8.setText("Incapacidad");

        grupoIncapacidad.add(radioIncapacidadSi);
        radioIncapacidadSi.setText("Sí");

        grupoIncapacidad.add(radioIncapacidadNo);
        radioIncapacidadNo.setText("No");

        jLabel9.setText("Alergías");

        grupoAlergia.add(radioAlergiaSi);
        radioAlergiaSi.setText("Sí");

        grupoAlergia.add(radioAlergiaNo);
        radioAlergiaNo.setText("No");

        jLabel10.setText("¿Suele hacer ejercicios?");

        grupoEjercicio.add(radioEjercicioSi);
        radioEjercicioSi.setText("Sí");

        grupoEjercicio.add(radioEjercicioNo);
        radioEjercicioNo.setText("No");

        jLabel11.setText("¿Tiende a desayunar?");

        grupoDesayuno.add(radioDesayunoSi);
        radioDesayunoSi.setText("Sí");

        grupoDesayuno.add(radioDesayunoNo);
        radioDesayunoNo.setText("No");

        jLabel12.setText("Tabaquismo");

        grupoTabaquismo.add(radioTabaquismoSi);
        radioTabaquismoSi.setText("Sí");

        grupoTabaquismo.add(radioTabaquismoNo);
        radioTabaquismoNo.setText("No");

        jLabel13.setText("Alcoholismo");

        grupoAlcoholismo.add(radioAlcoholismoSi);
        radioAlcoholismoSi.setText("Sí");

        grupoAlcoholismo.add(radioAlcoholismoNo);
        radioAlcoholismoNo.setText("No");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(radioIncapacidadSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioIncapacidadNo))
                    .addComponent(jLabel9)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(radioAlergiaSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioAlergiaNo))
                    .addComponent(jLabel10)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(radioEjercicioSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioEjercicioNo)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(radioTabaquismoSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioTabaquismoNo)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(radioDesayunoSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioDesayunoNo))
                            .addComponent(jLabel12)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(radioAlcoholismoSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioAlcoholismoNo)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioIncapacidadSi)
                    .addComponent(radioIncapacidadNo)
                    .addComponent(radioDesayunoSi)
                    .addComponent(radioDesayunoNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAlergiaSi)
                    .addComponent(radioAlergiaNo)
                    .addComponent(radioTabaquismoSi)
                    .addComponent(radioTabaquismoNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioEjercicioSi)
                    .addComponent(radioEjercicioNo)
                    .addComponent(radioAlcoholismoSi)
                    .addComponent(radioAlcoholismoNo))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Peso, tamaño, sangre"));

        jLabel14.setText("Peso");

        jLabel15.setText("Altura");

        jLabel16.setText("Tipo de sangre");

        jLabel26.setText("kilogramos");

        jLabel27.setText("metros");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(lblSangre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(tfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblSangre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Revisión de expediente");

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formularios/iconos/left-arrow.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel18.setText("Regresar");

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formularios/iconos/remove (1).png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Eliminar  ");

        btnAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formularios/iconos/information.png"))); // NOI18N
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        jLabel17.setText("Ayuda    ");

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formularios/iconos/setting.png"))); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel30.setText("Modificar  ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminar)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAyuda)
                                .addGap(18, 18, 18)
                                .addComponent(btnRegresar)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar)
                    .addComponent(btnEliminar)
                    .addComponent(btnAyuda)
                    .addComponent(btnModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(jLabel17)
                        .addComponent(jLabel30)))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Observaciones"));

        jLabel19.setText("Antecedentes hereditarios");

        jLabel20.setText("Antecedentes patológicos");

        areaNotasPaciente.setColumns(20);
        areaNotasPaciente.setRows(5);
        jScrollPane2.setViewportView(areaNotasPaciente);

        jLabel21.setText("Notas del paciente");

        jLabel2.setText("Horas de sueño");

        jLabel29.setText("Religion");

        jLabel31.setText("horas");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel21)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfPatologicos)
                            .addComponent(tfHereditarios))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel29)
                            .addComponent(tfReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(tfSueño, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfHereditarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPatologicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfReligion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Domicilio"));

        jLabel22.setText("Departamento");

        jLabel23.setText("Municipio");

        jLabel24.setText("N° Casa");

        jLabel25.setText("Telefono");

        jLabel28.setText("Direccion");

        areaDireccion.setColumns(20);
        areaDireccion.setRows(5);
        jScrollPane3.setViewportView(areaDireccion);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfMunicipio)
                                    .addComponent(tfDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                    .addComponent(tfTelefono))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tfDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(tfMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24)
                    .addComponent(tfCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Conexion conexion = new Conexion();
    private void tablaExpedienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaExpedienteMouseClicked
        // TODO add your handling code here:
        try {
            int fila = tablaExpediente.getSelectedRow();
            int id = Integer.parseInt(tablaExpediente.getValueAt(fila, 0).toString());
            
            Connection con = conexion.obtenerConexion();
            PreparedStatement ps;
            
            ps = con.prepareStatement("SELECT cedula, sexo, fNacimiento, telefono, departamento, municipio, numeroCasa, direccion, aIncapacidad, aHereditarios, aPatologicos, aAlergias, tipoSangre, eEjercicio, eDesayuno, horasSuenyo, religion, observacion, peso, altura, tabaquismo, alcoholismo FROM Datos WHERE idPaciente = ?");
            ps.setInt(1, id);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                lblId.setText(String.valueOf(id));
                lblCedula.setText(rs.getString("cedula"));
                lblSexo.setText(rs.getString("sexo"));
                tfPeso.setText(rs.getString("peso"));
                tfAltura.setText(rs.getString("altura"));
                lblSangre.setText(rs.getString("tipoSangre"));
                lblNacimiento.setText(rs.getString("fNacimiento"));
                tfDepartamento.setText(rs.getString("departamento"));
                tfMunicipio.setText(rs.getString("municipio"));
                tfCasa.setText(rs.getString("numeroCasa"));
                tfTelefono.setText(rs.getString("telefono"));
                
                DateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
                Date nacimiento = (Date) formato.parse(rs.getString("fNacimiento"));
                
                Calendar cumpleanyos = Calendar.getInstance();
                cumpleanyos.setTime(nacimiento);
                
                Calendar local = Calendar.getInstance();
                local.setTime(new Date());
                
                int edad = local.get(Calendar.YEAR) - cumpleanyos.get(Calendar.YEAR);
                lblEdad.setText(Integer.toString(edad));
                
                lblTipoDeFecha.setText("año-mes-día");
                
                areaDireccion.setText(rs.getString("direccion"));
                
                if (rs.getString("aIncapacidad").equals("Si")) {
                    radioIncapacidadSi.setSelected(true);
                } else if (rs.getString("aIncapacidad").equals("No")) {
                    radioIncapacidadNo.setSelected(true);
                }
                
                if (rs.getString("aAlergias").equals("Si")) {
                    radioAlergiaSi.setSelected(true);
                } else if (rs.getString("aAlergias").equals("No")) {
                    radioAlergiaNo.setSelected(true);
                }
                
                if (rs.getString("eEjercicio").equals("Si")) {
                    radioEjercicioSi.setSelected(true);
                } else if (rs.getString("eEjercicio").equals("No")) {
                    radioEjercicioNo.setSelected(true);
                }
                
                if (rs.getString("eDesayuno").equals("Si")) {
                    radioDesayunoSi.setSelected(true);
                } else if (rs.getString("eDesayuno").equals("No")) {
                    radioDesayunoNo.setSelected(true);
                }
                
                if (rs.getString("tabaquismo").equals("Si")) {
                    radioTabaquismoSi.setSelected(true);
                } else if (rs.getString("tabaquismo").equals("No")) {
                    radioTabaquismoNo.setSelected(true);
                }
                
                if (rs.getString("alcoholismo").equals("Si")) {
                    radioAlcoholismoSi.setSelected(true);
                } else if (rs.getString("alcoholismo").equals("No")) {
                    radioAlcoholismoNo.setSelected(true);
                }
                
                tfHereditarios.setText(rs.getString("aHereditarios"));
                tfPatologicos.setText(rs.getString("aPatologicos"));
                tfSueño.setText(rs.getString("horasSuenyo"));
                tfReligion.setText(rs.getString("religion"));
                
                areaNotasPaciente.setText(rs.getString("observacion"));
            }
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }

    }//GEN-LAST:event_tablaExpedienteMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        int fila = tablaExpediente.getSelectedRow();
        int id = Integer.parseInt(tablaExpediente.getValueAt(fila, 0).toString());
        
        String departamento = tfDepartamento.getText();
        String municipio = tfMunicipio.getText();
        String nCasa = tfCasa.getText();
        String telefono = tfTelefono.getText();
        String direccion = areaDireccion.getText();
        String horasSuenyo = tfSueño.getText();
        String religion = tfReligion.getText();
        String patologico = tfPatologicos.getText();
        String hereditario = tfHereditarios.getText();
        String peso = tfPeso.getText();
        String altura = tfAltura.getText();
        String observaciones = areaNotasPaciente.getText();
        
        String ejercicios;
        if (radioEjercicioSi.isSelected()) {
            ejercicios = "Si";
        } else if (radioEjercicioNo.isSelected()) {
            ejercicios = "No";
        } else {
            ejercicios = "No";
        }
        
        String desayuno;
        if (radioDesayunoSi.isSelected()) {
            desayuno = "Si";
        } else if (radioDesayunoNo.isSelected()) {
            desayuno = "No";
        } else {
            desayuno = "No";
        }
        
        String alergia;
        if (radioAlergiaSi.isSelected()) {
            alergia = "Si";
        } else if (radioAlergiaNo.isSelected()) {
            alergia = "No";
        } else {
            alergia = "No";
        }
        
        String tabaquismo;
        if (radioTabaquismoSi.isSelected()) {
            tabaquismo = "Si";
        } else if (radioTabaquismoNo.isSelected()) {
            tabaquismo = "No";
        } else {
            tabaquismo = "No";
        }
        
        String alcoholismo;
        if (radioAlcoholismoSi.isSelected()) {
            alcoholismo = "Si";
        } else if (radioAlcoholismoNo.isSelected()) {
            alcoholismo = "No";
        } else {
            alcoholismo = "No";
        }
        
        String incapacidad;
        if (radioIncapacidadSi.isSelected()){
            incapacidad = "Si";
        } else if (radioIncapacidadNo.isSelected()) {
            incapacidad = "No";
        } else {
            incapacidad = "No";
        }
        
        
        try {
            Connection con = conexion.obtenerConexion();
            PreparedStatement ps = con.prepareStatement("UPDATE Datos SET departamento = ?, municipio = ?, numeroCasa = ?, telefono = ?, direccion = ?,  aHereditarios = ?, aPatologicos = ?, aAlergias = ?, eEjercicio = ?, eDesayuno = ?, horasSuenyo = ?, religion = ?, observacion = ?, peso = ?, altura = ?, tabaquismo = ?, alcoholismo = ?, aIncapacidad = ? FROM Datos WHERE idPaciente = ?");
            ps.setString(1, departamento);
            ps.setString(2, municipio);
            ps.setString(3, nCasa);
            ps.setString(4, telefono);
            ps.setString(5, direccion);
            ps.setString(6, hereditario);
            ps.setString(7, patologico);
            ps.setString(8, alergia);
            ps.setString(9, ejercicios);
            ps.setString(10, desayuno);
            ps.setString(11, horasSuenyo);
            ps.setString(12, religion);
            ps.setString(13, observaciones);
            ps.setString(14, peso);
            ps.setString(15, altura);
            ps.setString(16, tabaquismo);
            ps.setString(17, alcoholismo);
            ps.setString(18, incapacidad);
            ps.setInt(19, id);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "El expediente id:" + id + " ha sido modificado");
            cargarDatos();
            limpiarCampos();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btnModificarActionPerformed
    
    private void limpiarCampos() {
        lblId.setText("");
        lblCedula.setText("");
        lblSexo.setText("");
        lblSangre.setText("");
        lblNacimiento.setText("");
        lblEdad.setText("");
        tfTelefono.setText("");
        tfHereditarios.setText("");
        tfPatologicos.setText("");
        tfReligion.setText("");
        tfSueño.setText("");
        areaNotasPaciente.setText("");
        tfPeso.setText("");
        tfAltura.setText("");
        tfDepartamento.setText("");
        tfMunicipio.setText("");
        tfCasa.setText("");
        areaDireccion.setText("");
        
        if (radioIncapacidadSi.isSelected()) {
            radioIncapacidadSi.setSelected(false);
        } else if (radioIncapacidadNo.isSelected()) {
            radioIncapacidadNo.setSelected(false);
        }
        
        if (radioAlergiaSi.isSelected()) {
            radioAlergiaSi.setSelected(false);
        } else if (radioAlergiaNo.isSelected()) {
            radioAlergiaNo.setSelected(false);
        }
        
        if (radioEjercicioSi.isSelected()){
            radioEjercicioSi.setSelected(false);
        } else if (radioEjercicioNo.isSelected()){
            radioEjercicioNo.setSelected(false);
        }
        
        if (radioDesayunoSi.isSelected()) {
            radioDesayunoSi.setSelected(false);
        } else if (radioDesayunoNo.isSelected()) {
            radioDesayunoNo.setSelected(false);
        }
        
        if (radioTabaquismoSi.isSelected()) {
            radioTabaquismoSi.setSelected(false);
        } else if (radioTabaquismoNo.isSelected()) {
            radioTabaquismoNo.setSelected(false);
        }
        
        if (radioAlcoholismoSi.isSelected()) {
            radioAlcoholismoSi.setSelected(false);
        } else if (radioAlcoholismoNo.isSelected()) {
            radioAlcoholismoNo.setSelected(false);
        }
    }
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = tablaExpediente.getSelectedRow();
        
        if (fila != -1) {
            int id = Integer.parseInt(lblId.getText().toString());
            String nombre = tablaExpediente.getValueAt(fila, 1).toString();
            
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea eliminar el paciente id: " + id + ", " + nombre + " ?", "Confirmar acción", JOptionPane.WARNING_MESSAGE);
            
            if (confirmacion == 0) {
                DatoControlador datoControlador = new DatoControlador();
                boolean respuesta = datoControlador.eliminar(id);
                
                if (respuesta) {
                    JOptionPane.showMessageDialog(null, "Se eliminó correctamente la información del paciente " + id + ", " + nombre, "Registro eliminado", JOptionPane.INFORMATION_MESSAGE);
                    
                    cargarDatos();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Acción cancelada", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Menu regresar = new Menu();
        regresar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Panel de ayuda\n\n"
                + "Visualizar datos del paciente: \n"
                + "Para visualizar los datos del paciente dé clic sobre una fila de la tabla,\n"
                + "esto hará que los datos se impriman en cada plantilla del formulario y puedan visualizarse.\n\n"
                + "Modificar datos del paciente: \n"
                + "Para modificar los datos del paciente tendrá que seleccionarlo de la tabla, pero\n"
                + "una vez hecho eso los únicos campos modificables son los campos en blanco que permiten\n"
                + "la ingresión de la entrada del teclado. Una vez reemplazados los datos de los campos\n"
                + "presionamos el botón \"Modificar\" y esto actualizará la base de datos del paciente.", "Ayuda", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAyudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public void cargarDatos() {
        String[] nombreColumnas = {"Id", "Nombres", "Apellidos"};
        DefaultTableModel modelo = new DefaultTableModel(null, nombreColumnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        DatoControlador datoControlador = new DatoControlador();
        List<Dato> listaDatos = datoControlador.listar();
        
        for (Dato dato : listaDatos) {
            Object[] data = new Object[nombreColumnas.length];
            data[0] = dato.getId();
            data[1] = dato.getPrimerNombre() + " " + dato.getSegundoNombre();
            data[2] = dato.getPrimerApellido() + " " + dato.getSegundoApellido();
            
            modelo.addRow(data);
        }
        tablaExpediente.setModel(modelo);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RevisionExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RevisionExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RevisionExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RevisionExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RevisionExpediente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDireccion;
    private javax.swing.JTextArea areaNotasPaciente;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.ButtonGroup grupoAlcoholismo;
    private javax.swing.ButtonGroup grupoAlergia;
    private javax.swing.ButtonGroup grupoDesayuno;
    private javax.swing.ButtonGroup grupoEjercicio;
    private javax.swing.ButtonGroup grupoIncapacidad;
    private javax.swing.ButtonGroup grupoTabaquismo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNacimiento;
    private javax.swing.JLabel lblSangre;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTipoDeFecha;
    private javax.swing.JRadioButton radioAlcoholismoNo;
    private javax.swing.JRadioButton radioAlcoholismoSi;
    private javax.swing.JRadioButton radioAlergiaNo;
    private javax.swing.JRadioButton radioAlergiaSi;
    private javax.swing.JRadioButton radioDesayunoNo;
    private javax.swing.JRadioButton radioDesayunoSi;
    private javax.swing.JRadioButton radioEjercicioNo;
    private javax.swing.JRadioButton radioEjercicioSi;
    private javax.swing.JRadioButton radioIncapacidadNo;
    private javax.swing.JRadioButton radioIncapacidadSi;
    private javax.swing.JRadioButton radioTabaquismoNo;
    private javax.swing.JRadioButton radioTabaquismoSi;
    private javax.swing.JTable tablaExpediente;
    private javax.swing.JTextField tfAltura;
    private javax.swing.JTextField tfCasa;
    private javax.swing.JTextField tfDepartamento;
    private javax.swing.JTextField tfHereditarios;
    private javax.swing.JTextField tfMunicipio;
    private javax.swing.JTextField tfPatologicos;
    private javax.swing.JTextField tfPeso;
    private javax.swing.JTextField tfReligion;
    private javax.swing.JTextField tfSueño;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
